name = "pathshare"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "pathshare-db"
database_id = "cc96adee-f03a-49a3-a6bc-c39171cb9ad3"
migrations_dir = "migrations"
